### ISSUE TITLE
Add additional JS options

### ISSUE THREAD

**Issue by jasondavis** [ryanpcmcquen/cheval#10]
A feature request is to allow to define some custom options.

One in particular is this `setCopyBtnText('Copy again');` would be nice to allow user to set the text value.  In my current usage this new text breaks my layout as it makes my button wider

**Comment by ryanpcmcquen** [comment]
I am not 100% opposed to this ... what would you change the text to?

**Comment by jasondavis** [comment]
I have 2 ideas....

## Idea Number 1

Modify current code or create a 2nd version which allows user to make an instance of the library like this below instead of scanning the DOM you would be able to pass in the selectors for each instance of a copy button and set the properties on a per button basis.  This would make it faster as well I believe...

    // custom options for cheval copy to clipboard library
    var copy_to_clipboard_options = {
        textClassName: 'text-to-copy',
        buttonClassName: 'js-copy-btn',
        copyBtnText: {
            repeatCopy: 'Copy again',
            iphoneOrIpodCopy: 'Now tap Copy',
            ipadCopy: 'Now tap the text, then Copy',
            oldSafariCopy: 'Press Command + C to copy',
            copyNotSupported: 'Please copy manually'
        }
    };

    // pass cheval options into object and initiate
    var copy_to_clipboard = new Cheval(copy_to_clipboard_options);

---

## Idea Number 2

This version is the quick simple fix of just changing the hard codes text into variables in the library code to make it easier to modify....

In the current `cheval.js` file on lines   [27 and 28](https://github.com/ryanpcmcquen/cheval/blob/gh-pages/cheval.js#L27-L28) are these two variables.  You could simple add a new variable to hold the button text options and if someone wants to modify the text they can modify the library code for those variables. 

    var textClassName = 'text-to-copy';
    var buttonClassName = 'js-copy-btn';

    var  copyBtnText = {
           repeatCopy: 'Copy again',
          iphoneOrIpodCopy: 'Now tap Copy',
          ipadCopy: 'Now tap the text, then Copy',
          oldSafariCopy: 'Press Command + C to copy',
          copyNotSupported: 'Please copy manually'
      };

**Comment by jasondavis** [comment]
For idea #2 I did a quick demo here http://www.apollowebstudio.com/labs/cheval-copy-to-clipboard-buttons-js-lib.html

The text strings are the same as the current library but they are pulled from a variable now

---

## UPDATE

This image below shows my 2 buttons I am using the copy button on to copy URLs.  

I am now going to add the copy feature to the color preview squares in the image to copy the color HEX codes.  

So I am going to modify the code again so when it sees a word like `none` for one of the button text variables it will not update that buttons text at all for cases like this color example...

![image](https://cloud.githubusercontent.com/assets/186818/23690640/4833e422-0391-11e7-8bee-ba56e7c5f243.png)

---

## UPDATE 2

I'm in a rush so I just did a quick update to disable all button text updates with a variable `var canUpdateButtonText = false;` and then wrapped this block...

    // if update button text enable then update button text after clicking on it
    if(canUpdateButtonText){
      if (oldSafari) {
        if (iPhoneORiPod) {
          setCopyBtnText(copyBtnText.iphoneOrIpodCopy);
        } else if (iPad) {
          // The iPad doesn't have the 'Copy' box pop up,
          // you have to tap the text first.
          setCopyBtnText(copyBtnText.ipadCopy);
        } else {
          // Just old!
          setCopyBtnText(copyBtnText.oldSafariCopy);
        }
      } else {
        setCopyBtnText(copyBtnText.repeatCopy);
      }
    }

**Comment by ryanpcmcquen** [comment]
For now I prefer idea [#2](https://github.com/ryanpcmcquen/cheval/issues/10#issuecomment-284940945) with the `canUpdateButtonText` variable. Although I may add a front-facing API in the future, having _no_ API has helped the library's approach-ability and accessibility. I will get started on making these changes unless you want to PR?

**Comment by jasondavis** [comment]
+I can push what I did when I get time if you want to look at it and decide if u wanna pull it in

**Comment by ryanpcmcquen** [comment]
Excellent, I would love to take a look. Thank you!

**Comment by jasondavis** [comment]
The pull request I sent is this file 

Button Text Updates - https://www.apollowebstudio.com/labs/cdn/cheval-copy-to-clipboard-js/cheval-copy-to-clipboard.js

Working demo of that file hereon the color squares and url inputs - https://jsfiddle.net/jasondavis/L6zu4trj/

**Comment by ryanpcmcquen** [comment]
@jasondavis did you see my message in the PR?

**Comment by ryanpcmcquen** [comment]
@jasondavis thanks for the issue and PR, `1.1.0` incorporates changes that allow easily editing the text, you've been given much deserved kudos in the commits and release!

https://github.com/ryanpcmcquen/cheval/releases
