### ISSUE TITLE
Initialize Cheval with JS

### ISSUE THREAD

**Issue by jasondavis** [ryanpcmcquen/cheval#12]
The current drop-in library is nice for some use cases but in a large JS App where HTML content in the DOM is constantly being added and replaced with new screens/views of the app, the current library is not able to work as it only runs on HTML items that are in the DOM when the page is loaded.

If there was an alternate version or method added to allow initializing the library from code it could then be ran each time the DOM content is changed that needs copy capability

**Comment by ryanpcmcquen** [comment]
I agree.

**Comment by ryanpcmcquen** [comment]
I'm thinking leaving the current version as is and presenting a version through `npm` that is _only_ initialized with JS, thoughts?

**Comment by ryanpcmcquen** [comment]
@jasondavis just waiting for this to propagate: https://cdn.jsdelivr.net/gh/ryanpcmcquen/cheval@latest/gCheval.js
