### ISSUE TITLE
Hiding the textarea

### ISSUE THREAD

**Issue by LeaVerou** [ryanpcmcquen/cheval#2]
I found the restriction in the readme interesting, so I peeked at the code.
It looks like you need it to not be hidden so you can execute `.select()` and then `execCommand`. This is also probably why you need a textarea.
However, wouldn't this be solved if you just created a (visible, off-screen) textarea on the fly with whatever content the user wants to copy, then destroyed it after the copy? That way you could copy the content of any element, not just textareas.

**Comment by ryanpcmcquen** [comment]
@LeaVerou ooh! I like that! I'll start working on this. Of course, pull requests are good too. :wink:

**Comment by ryanpcmcquen** [comment]
It's not ready for prime time, but I have begun initial work in this branch: https://github.com/ryanpcmcquen/simpleJsCopy/tree/useAnyElement

**Comment by ryanpcmcquen** [comment]
@LeaVerou is this close to what you were thinking?

https://jsfiddle.net/ryanpcmcquen/kt2mc8v6/

You can also test locally with the [useAnyElement](https://github.com/ryanpcmcquen/simpleJsCopy/tree/useAnyElement) branch. :tada:

If it works, I'll update everything and push out `0.3.0`!

**Comment by ryanpcmcquen** [comment]
So it kind of works, sadly it still needs to be a `textarea` on Safari (< v10). The off screen one just causes craziness. Good news is Safari 10 totally supports `execCommand('copy')`!
