### ISSUE TITLE
Screen jumps to bottom after click 

### ISSUE THREAD

**Issue by torbentschechne** [ryanpcmcquen/cheval#6]
Hello,
I use cheval.min.js and each time I click on the copy button, it copies correctly, but also the screen jumps to the bottom.

I assume an event.preventDefault(); is missing, but I saw that the event is never established in the js. Can you help how to fix it?

Thanks!

**Comment by ryanpcmcquen** [comment]
I've noticed this. A `preventDefault` may prevent the text from copying ... I will see what I can figure out.

**Comment by ryanpcmcquen** [comment]
@elbsurfer, is this what you are noticing?

https://app.hyfy.io/v/ab4MC62DgD/

**Comment by torbentschechne** [comment]
Yes @ryanpcmcquen

**Comment by ryanpcmcquen** [comment]
That's default behavior for an area receiving focus/being selected. Is it causing a problem in your app/site?

**Comment by torbentschechne** [comment]
Yes, it's a bit disturbing when you can see the button initially, click on it and the page jumps to the bottom.

**Comment by ryanpcmcquen** [comment]
Does this work as you would want it to? https://jsfiddle.net/ryanpcmcquen/2nm87h8o/

**Comment by torbentschechne** [comment]
Looks good.

**Comment by ryanpcmcquen** [comment]
New release is up! Thanks for the bug report. :smile_cat:
