### ISSUE TITLE
Doesn't work with Google Chrome on Windows

### ISSUE THREAD

**Issue by jasondavis** [ryanpcmcquen/cheval#8]
Doesn't work with Google Chrome on Windows

**Comment by ryanpcmcquen** [comment]
Are you just testing the main page or is it on a site you can share?

**Comment by ryanpcmcquen** [comment]
Will you try this version?

https://cheval-ryanpcmcquen.c9users.io/index.html

**Comment by ryanpcmcquen** [comment]
This appears to not be OS-related, and rather a regression introduced in [1.0.4](https://github.com/ryanpcmcquen/cheval/releases/tag/1.0.4). This commit in particular: https://github.com/ryanpcmcquen/cheval/commit/fb5490b8ad41405e17f162ee80e00f8b4f7771ea

Moving where the disable happens does appear to fix it, but I will wait for your confirmation before pushing out `1.0.5`.

**Comment by ryanpcmcquen** [comment]
Closing this for now as I believe it is fixed, please reopen if you find the issue is still present.

**Comment by jasondavis** [comment]
Sorry for the delay I didn't see this.  This link https://cheval-ryanpcmcquen.c9users.io/index.html is working on my Chrome.  Thanks
